---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: 26.0.0
    chart: traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
