---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipam
  namespace: metallb-system
spec:
  addresses:
  - 172.18.255.225-172.18.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
