---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit-cert-manager
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit-cert-manager
  namespace: cert-manager
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit-cert-manager
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubernetes-toolkit
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit-cert-manager
    namespace: cert-manager
