---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

# To upgrade ArgoCD, increment the version here
# https://github.com/argoproj/argo-cd/tags
resources:
  - github.com:argoproj/argo-cd.git/manifests/cluster-install?ref=v2.6.4
  - argocd-namespace.yml
  - argocd-ui-ingress.yml
  - argocd-ui-ingressroute.yml

patches:
  - path: argocd-cm.yml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-cmd-params-cm.yml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
