---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ./namespace.yml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- ./ingress.yml

patches:
- path: config.yml
  target:
    kind: ConfigMap
    name: argocd-cm
