apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ./namespace.yml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- ./application.yml

patches:
- path: loadbalancer-patch.yml
  target:
    kind: Service
    name: argocd-server
