---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: v0.13.12
    helm:
      values: |-
        configInline:
          address-pools:
            - name: default
              protocol: layer2
              addresses:
                - 172.19.255.200-172.19.255.250
    chart: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
