---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
- https://raw.githubusercontent.com/metallb/metallb/main/config/manifests/metallb-native.yaml
- ./metallb-ipam.yml
